const COLOR_WHITE = '#FFFFFF';
const COLOR_GRAY = '#E5E5E5';
const COLOR_GRAY01 = '#C4C4C4';
const COLOR_BLACK = '#333333';

const COLOR_GREEN_ORANGE = '#7CD685';
const COLOR_RED_BLUE = '#FF796A';
const COLOR_YELLOW_PURPLE = '#FFBE5C';
const COLOR_BROWN_PINK = '#C79172';
const COLOR_PURPLE_YELLOW = '#B883EE';
const COLOR_BLUE_RED = '#379FFF';

const TEXT_FILED_HINT_COLOR = '#d4d4d4';
const INPUT_FILTER_TILE_COLOR = '#F8F8F8';
